describe("pizza form test", ()=>{

    const fname = ()=>cy.get("input[name=fname]")
    const lname = ()=>cy.get("input[name=lname]")
    const pizzaSize = ()=>cy.get("select[name=pizzaSize]")
    const pepperoni = ()=>cy.get("input[name=pepperoni]")
    const cheese = ()=>cy.get("input[name=cheese]")
    const sausage = ()=>cy.get("input[name=sausage]")
    const jalapenos = ()=>cy.get("input[name=jalapenos]")
    const canadianBacon = ()=>cy.get("input[name='canadian bacon']")
    const onions = ()=>cy.get("input[name=onions]")
    const olives = ()=>cy.get("input[name=olives]")
    const pineapples = ()=>cy.get("input[name=pineapples]")
    const scorpionPeppers = ()=>cy.get("input[name='scorpion peppers']")
    const submit = ()=>cy.get("button[id=submit]")

    beforeEach(()=>{
        cy.visit('http://localhost:3000/pizza')
    })

    it("Check form exists", ()=>{
        fname().should("exist") 
        lname().should("exist")
        pizzaSize().should("exist")
        pepperoni().should("exist")
        cheese().should("exist")
        sausage().should("exist")
        jalapenos().should("exist")
        canadianBacon().should("exist")
        onions().should("exist")
        olives().should("exist")
        pineapples().should("exist")
        scorpionPeppers().should("exist")
        submit().should("exist").should("be.disabled")
    })

    it("Check form submissions", ()=>{
        fname()
            .type("done")
        lname()
            .type("done")
        pizzaSize()
            .select("Small")
        pepperoni()
            .check()
        cheese()
            .check()
        sausage()
            .check()
        jalapenos()
            .check()
        canadianBacon()
            .check()
        onions()
            .check()
        olives()
            .check()
        pineapples()
            .check()
        scorpionPeppers()
            .check()
        submit().should("not.be.disabled").click()
    })
})